version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=feli
      - POSTGRES_PASSWORD=felicontraseña
      - POSTGRES_DB=fastapi
    deploy:
      resources:
        limits:
          memory: 1G


  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G