version: "3.8"
services:

  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # - DATABASE_HOST=127.0.0.1
      # - POSTGRES_USER=feli
      - POSTGRES_PASSWORD=felicontraseña
      - POSTGRES_DB=fastapi
    volumes:
      - db:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  db:
